### ISSUE TITLE
https://betterdiscordlibrary.com/themes/Rem

### ISSUE THREAD

**Issue by XzadikApple** [ShadowDevilsAvenged/ShadowDevilsAvenged#25]
Background image file does not load. Checked source code and seems like link access has been denied

https://images8.alphacoders.com/103/1034438.png

any way you can get this image back up?

**Comment by ShadowDevilsAvenged** [comment]
The image shows up for me

**Comment by XzadikApple** [comment]
There’s might have been a website outage at the time of the issue. Seems to
load now.
