### ISSUE TITLE
New Rem Theme: Sticker Window too small(?)

### ISSUE THREAD

**Issue by shikiddo** [ShadowDevilsAvenged/ShadowDevilsAvenged#37]
![issue_sticker](https://user-images.githubusercontent.com/18443226/176431798-4e89b6b4-91d9-48cb-a3a4-bdadfe3c7501.png)

The sticker window is too small(?)

**Comment by ShadowDevilsAvenged** [comment]
The sticker window doesn't feel that small to me

**Comment by xNudele** [comment]
Can you bring discord winter return theme back?

wt., 4 paź 2022 o 00:00 ShadowDevilsAvenged ***@***.***>
napisał(a):
