### ISSUE TITLE
New Rem theme red mark 

### ISSUE THREAD

**Issue by moosje2003** [ShadowDevilsAvenged/ShadowDevilsAvenged#38]
when I go into the theme editor the Atribute "RX" is marked in red what can i do about that?
![image](https://user-images.githubusercontent.com/61630365/201109591-3d71b0f9-083a-4dbb-82e6-28a64e72432b.png)

**Comment by ShadowDevilsAvenged** [comment]
Oh ignore that it's supposed to happen because I changed the shape of the switch it shouldn't affect the theme itself

**Comment by moosje2003** [comment]
Okay thanks
