### ISSUE TITLE
There are some issues with the new experimental backgroundcolors from discord

### ISSUE THREAD

**Issue by Reedix7** [ShadowDevilsAvenged/ShadowDevilsAvenged#39]
The shape of the channels get changed, but the backgroundimage doesn´t change.
![Screenshot 2023-03-27 170404](https://user-images.githubusercontent.com/74781972/227980990-5f1e5a56-1b1b-4dfb-b9ec-1e37757128d5.png)
I don´t know if this comment is helpful, but yeah. It would be awesome when it gets fixed, because it´s my favourite theme (I talk about the old and new akame ga kill theme, both doesnt work)

**Comment by ShadowDevilsAvenged** [comment]
Yeah it should work again try reinstalling the theme

**Comment by ShadowDevilsAvenged** [comment]
Is the issue resolved
